# Generated by Django 3.2.15 on 2023-08-03 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceGeoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='широта')),
                ('lon', models.FloatField(verbose_name='долгота')),
                ('address', models.CharField(max_length=200, null=True)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('uid', models.PositiveBigIntegerField(db_index=True, unique=True)),
            ],
        ),
    ]
