# Generated by Django 3.2.15 on 2023-08-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maptools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placegeoinfo',
            name='uid',
        ),
        migrations.AlterField(
            model_name='placegeoinfo',
            name='address',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
