# Generated by Django 3.2.15 on 2023-08-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maptools', '0003_alter_placegeoinfo_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placegeoinfo',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='placegeoinfo',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='долгота'),
        ),
    ]
