# Generated by Django 3.2.15 on 2023-07-18 09:07

from django.db import migrations
from foodcartapp.models import Item


def set_price(apps, schema_editor):
    items = Item.objects.all()
    for item in items:
        item.price = item.product.price * item.quantity
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0004_item_price'),
    ]

    operations = [
        migrations.RunPython(set_price)
    ]
