# Generated by Django 3.2.15 on 2023-07-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0005_auto_20230718_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RC', 'RECEIVED'), ('PR', 'PREPARING'), ('DL', 'DELIVERING'), ('FN', 'FINISHED')], default='RECEIVED', max_length=20),
        ),
    ]
