# Generated by Django 3.2.15 on 2023-07-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0010_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CS', 'CASH'), ('CD', 'CARD')], db_index=True, default='CARD', max_length=20),
        ),
    ]
