# Generated by Django 3.2.15 on 2023-07-30 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0011_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prepared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant', verbose_name='ресторан, принявший заказ'),
        ),
    ]
