# Generated by Django 3.2.15 on 2023-07-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0013_alter_order_prepared_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('1', 'CASH'), ('2', 'CARD')], db_index=True, default='CARD', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'RECEIVED'), ('2', 'PREPARING'), ('3', 'DELIVERING'), ('4', 'FINISHED')], db_index=True, default='RECEIVED', max_length=20),
        ),
    ]
