# Generated by Django 3.2.15 on 2023-07-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0014_auto_20230730_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('1', 'CARD'), ('2', 'CASH')], db_index=True, default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'RECEIVED'), ('2', 'PREPARING'), ('3', 'DELIVERING'), ('4', 'FINISHED')], db_index=True, default='1', max_length=20),
        ),
    ]
