# Generated by Django 3.2.15 on 2023-06-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_order_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='qty',
            new_name='quantity',
        ),
    ]
